" File: .vimrc
" Version: 1
" Author: Shunchao Wang
" Created: Jan 23, 2013

" User vim settings, rather than VI settings
set nocompatible
filetype off	"required
filetype plugin indent on	"required

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let vundle manage vundle
" required
Bundle 'gmarik/vundle'

" My bundles here
" 
" original repos on github
Bundle 'xolox/vim-misc'
Bundle 'xolox/vim-notes'
Bundle 'altercation/vim-colors-solarized'
Bundle 'scrooloose/nerdtree'
Bundle 'Raimondi/delimitMate'
Bundle 'Yggdroot/indentLine'
Bundle 'ervandew/supertab'
Bundle 'sirVer/ultisnips'
" Ultisnips useful snippets
Bundle 'honza/vim-snippets'
Bundle 'kien/ctrlp.vim'
Bundle 'tomtom/tcomment_vim'
Bundle 'majutsushi/tagbar'
Bundle 'xolox/vim-easytags'

" Turn on the verboseness to see everything vim is doing
" set verbose=9

" I like 4 spaces for indenting
set shiftwidth=4

" force columns to be 80 autowrap
set textwidth=80

" I like 4 stops
" softtabstop will make backspace to remove already input tab
" tabstop needs to backspace 4 times to remove an input tab
set tabstop=4
set softtabstop=4

" Spaces instead of tabs
set expandtab

" Always set auto indenting on
set autoindent

" set command height
set cmdheight=2

" do not keep a backup files
set nobackup
set nowritebackup
set noswapfile

" keep 20 lines of command line history
set history=20

" show the cursor position all the time
set ruler

" show (partial) command
set showcmd

" set ignorecase on and incremental search
set ignorecase
set incsearch

" set status line
set statusline=[%02n]\ %f\ %(\[%M%R%H]%)%=\ %4l,%02c%2V\ %P%*

" Always display a status line at the bottom of the window
set laststatus=2

" Showmatch: show the matching bracket for the last ')'?
set showmatch

" Allow tilde to act as an operator
set notildeop

" Turn on syntax
syntax on

" Vertical line indentation
let g:indentLine_color_term = 239
"let g:indentLine_color_gui = '#09AA08'
let g:indentLine_char = '|'
" DelimitMate setting
" let delimitMate_expand_cr = 1

" set encoding, fileencoding, fileencodings
set encoding=utf-8
" set langmenu=zh_CN.UTF-8
" language message zh_CN.UTF-8
" set new file encoding
set fileencoding=utf-8
" set file encoding order
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1

" notes setting
let g:notes_directories = ['~/.vim/Notes']
let g:notes_suffix = '.txt'
let g:notes_title_sync = 'rename_file'

" color theme setting
set background=dark " light for light version
if has('gui_running')
    colorscheme solarized
    set background=dark " dark or light
    set guifont=Monaco:h15
    set columns=150 lines=45
    set fuoptions=maxvert,maxhorz
endif

" NERDTree setting
nnoremap <silent> <Leader>n :NERDTreeToggle<CR>
" Uncomment this if you want to lose NERDTree if it is the last window open
" autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
let g:NERDTreeChDirMode = 2
let g:NERDTreeWinSize = 35

" CtrlP setting
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'rw'
let g:ctrlp_by_filename = 1
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.class,*.jar,*.war,*.o,.DS_Store
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'

" Ultisnips setting
let g:UltiSnipsExpandTrigger="ii"
let g:UltiSnipsListSnippets="iI"
let g:UltiSnipsJumpForwardTrigger="II"
let g:UltiSnipsJumpBackwardTrigger="OO"

" Tagbar settings
nnoremap <silent> <Leader>t :TagbarToggle<CR>
let g:tagbar_ctags_bin='/usr/local/bin/ctags'
let g:tagbar_width=31

"" Tagbar groovy support
let g:tagbar_type_groovy = {
    \ 'ctagstype' : 'groovy',
    \ 'kinds' : [
    \ 'p:package',
    \ 'c:class',
    \ 'i:interface',
    \ 'f:function',
    \ 'v:variables'
    \ ]
\ }

" vim-easytags settings
" Easytags (enables CTL-] and CTRL-T) by autotagging
let g:easytags_cmd = '/usr/local/bin/ctags'
set tags=./.git/tags;~/.vimtags
let g:easytags_dynamic_files = 1

