if [ -e ~/.bashrc  ]
then
    . ~/.bashrc
fi

# Triton ssh aliases to dev machines on RDMZ
alias sshTritonUI='ssh -2 -X cagrid@triton.bmi.osumc.edu'
alias sshTritonDS='ssh -2 -X cagrid@triton-directory.bmi.osumc.edu'
alias sshTritonPS='ssh -2 -X cagrid@triton-protocol.bmi.osumc.edu'
alias sshTritonPaS='ssh -2 -X cagrid@triton-participant.bmi.osumc.edu'
alias sshTritonTS='ssh -2 -X cagrid@triton-tissue.bmi.osumc.edu'
alias sshCSM='ssh -2 -X cagrid@csm.bmi.osumc.edu'
alias sshRIEQP='ssh -2 -X wan119@hcl-qp-dev.bmi.osumc.edu'
alias sshCIE='ssh -2 -X wan119@140.254.126.244'

WORKSHOP=~/Workshop

export CATALINA_HOME=${WORKSHOP}/apache-tomcat-7.0.52
ANT_HOME=${WORKSHOP}/apache-ant-1.9.3
MVN_HOME=${WORKSHOP}/apache-maven-3.2.1
GRAILS_HOME=${WORKSHOP}/grails-2.3.7
JAVA6_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
JAVA7_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_21.jdk/Contents/Home
export JAVA_HOME=${JAVA7_HOME}

export PATH=/usr/local/bin:${ANT_HOME}/bin:${MVN_HOME}/bin:${GRAILS_HOME}/bin:$PATH
