if [ -e ~/.bashrc  ]
then
    . ~/.bashrc
fi

WORKSHOP=~/Workshop
WORKSPACE=~/Workspace

export CATALINA_HOME=${WORKSHOP}/apache-tomcat-7.0.19
ANT_HOME=${WORKSHOP}/apache-ant-1.8.4
MVN_HOME=${WORKSHOP}/apache-maven-3.1.1
GRAILS_HOME=${WORKSHOP}/grails-2.3.6
export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

export PATH=${ANT_HOME}/bin:${MVN_HOME}/bin:${GRAILS_HOME}/bin:$PATH
