#! /bin/bash

# File to create new screen
r1='/dev/shm/screen'
r2=$(date +%s)
commandfile="$r1$r2"

rm -f $commandfile
cat ~/.screenrc > $commandfile

cat << EOF >> $commandfile
caption string '%t'
screen -t " Main"
screen -t " II"
screen -t " III"
screen -t " IV"
select " Main" 
EOF

screen -c $commandfile

rm -f $commandfile

