if [ -e ~/.bashrc  ]
then
    . ~/.bashrc
fi

export PATH=/usr/local/bin:$PATH 

# enable vi mode
# set -o vi # set -o emacs is to enable emacs default mode

# go lang
export GOPATH=~/Developer/go
export PATH=${GOPATH}/bin:$PATH

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/swang/.sdkman"
[[ -s "/Users/swang/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/swang/.sdkman/bin/sdkman-init.sh"
