
# Avoid successive duplicates in the bash command history
export HISTCONTROL=ignoredups

: '
 Append commands to the bash command history file (~/.bash_history)
 instead of overwriting it.
'
shopt -s histappend

: '
 Append commands to the history every time a prompt is shown,
 instaead of after closing the session.
'
PROMPT_COMMAND="history -a ; $PROMPT_COMMAND"

# set tab title to display the working dir
function set_tab_title {
    echo -n -e "\033]0;${PWD##*/}\007"
}

# add set tab title to PROMPT_COMMAND
PROMPT_COMMAND="set_tab_title ; $PROMPT_COMMAND"


# set xterm to be 256 colors instead of default ansi 8 colors
#export TERM=xterm-256color

# Add bash aliases.
if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

export EDITOR=vim

# Add bash aliases.
if [ -f ~/.myrc ]; then
    source ~/.myrc
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
#export SDKMAN_DIR="/Users/swang/.sdkman"
#[[ -s "/Users/swang/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/swang/.sdkman/bin/sdkman-init.sh"
